# The following manifests contain a certificate CR and possibly a self-signed issuer.
# More document can be found at https://docs.cert-manager.io
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert
spec:
  secretName: webhook-server-cert
  dnsNames:
  - netobserv-webhook-service.{{ .Release.Namespace }}.svc
  - netobserv-webhook-service.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
{{ if .Values.certManager.existingIssuer.name }}
  issuerRef:
    kind: {{ .Values.certManager.existingIssuer.kind }}
    name: {{ .Values.certManager.existingIssuer.name }}
{{ else }}
  issuerRef:
    kind: Issuer
    name: self-signed
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: self-signed
spec:
  selfSigned: {}
{{ end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: metrics-serving-cert
spec:
  secretName: manager-metrics-tls
  dnsNames:
  - netobserv-metrics-service.{{ .Release.Namespace }}.svc
  - netobserv-metrics-service.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
{{ if .Values.certManager.existingIssuer.name }}
  issuerRef:
    kind: {{ .Values.certManager.existingIssuer.kind }}
    name: {{ .Values.certManager.existingIssuer.name }}
{{ else }}
  issuerRef:
    kind: Issuer
    name: self-signed
---
{{ end }}
