apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: netobserv-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netobserv-manager-role
subjects:
  - kind: ServiceAccount
    name: netobserv-controller-manager
    namespace: netobserv
