apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: netobserv-openshift-netobserv-operator-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: netobserv-openshift-netobserv-operator-prometheus
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
