apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/component: rbac
  name: netobserv-bpfd-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bpfd-bpfprogramconfig-editor-role
subjects:
- kind: ServiceAccount
  name: netobserv-controller-manager
  namespace: netobserv
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/component: rbac
  name: netobserv-agent-bpfd-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bpfd-bpfprogramconfig-editor-role
subjects:
- kind: ServiceAccount
  name: netobserv-ebpf-agent
  namespace: netobserv-privileged