version: 2
outputDir: _tmp
apisToHide: []
apiMap:
- name: flows.netobserv.io
  resources:
  - kind: FlowCollector
    group: flows.netobserv.io
    version: v1beta2
  - kind: FlowMetric
    group: flows.netobserv.io
    version: v1alpha1
  - kind: FlowCollectorSlice
    group: flows.netobserv.io
    version: v1alpha1
