# This patch updates the version for default images
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/consolePlugin/properties/image/default
  value: "quay.io/netobserv/network-observability-console-plugin:$PLG_VERSION"
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/flowlogsPipeline/properties/image/default
  value: "quay.io/netobserv/flowlogs-pipeline:$FLP_VERSION"
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/agent/properties/ebpf/properties/image/default
  value: "quay.io/netobserv/netobserv-ebpf-agent:$BPF_VERSION"
