apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
## Append samples you want in your CSV to this file as resources ##
resources:
- flows_v1beta2_flowcollector.yaml
- flows_v1alpha1_flowmetric.yaml
- flows_v1alpha1_flowcollectorslice.yaml
