#flp_confgen
description:
  This metric observes the namespaces incoming traffic
details:
  Sum packets for incoming traffic per source and destination namespaces
usage:
  Evaluate network incoming usage breakdown per source and destination namespaces
tags:
  - ingress
  - packets
  - namespaces
encode:
  type: prom
  prom:
    metrics:
      - name: namespace_ingress_packets_total
        type: counter
        valuekey: Packets
        filter:
          key: FlowDirection
          value: "0"
        labels:
          - SrcK8S_Namespace
          - DstK8S_Namespace
