apiVersion: v2
name: netobserv-operator
description: Network Observability in Kubernetes based on eBPF.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.11.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: 1.11.0-community

keywords:
- netobserv
- ebpf
- ipfix
- flow tracing
- netflows
- topology
- network
- observability

home: https://netobserv.io/

sources:
- https://github.com/netobserv/network-observability-operator
- https://github.com/netobserv/flowlogs-pipeline
- https://github.com/netobserv/netobserv-ebpf-agent
- https://github.com/netobserv/network-observability-console-plugin
- https://github.com/netobserv/network-observability-cli

maintainers:
- email: jpinsonn@redhat.com
  name: Julien Pinsonneau
- email: jtakvori@redhat.com
  name: Joel Takvorian
- email: lberetta@redhat.com
  name: Leandro Beretta
- email: ljira@redhat.com
  name: Luis Jira
- email: mmahmoud2201@gmail.com
  name: Mohamed S. Mahmoud
- email: ocazade@redhat.com
  name: Olivier Cazade
- email: stlee@redhat.com
  name: Steven Lee

icon: https://netobserv.io/static/assets/images/netobserv.svg

annotations:
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: "Deep Insights"
  artifacthub.io/screenshots: |
    - title: Topology view
      url: https://netobserv.io/static/assets/images/about/topology-main.png
    - title: Flow details
      url: https://netobserv.io/static/assets/images/about/network-traffic-main.png

dependencies:
- name: prometheus
  version: "~28.2.0"
  repository: https://prometheus-community.github.io/helm-charts
  condition: install.prom
- name: kube-prometheus-stack
  version: "~80.4.1"
  repository: https://prometheus-community.github.io/helm-charts
  condition: install.prom-stack
- name: loki-stack
  version: "~2.10.3"
  repository: https://grafana.github.io/helm-charts
  condition: install.loki
